server:
  name: "project-api"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "C:\\Users\\17749\\GolandProjects\\project\\ms_project\\logs\\debug\\project-debug.log"
  infoFileName: "C:\\Users\\17749\\GolandProjects\\project\\ms_project\\logs\\info\\project-info.log"
  warnFileName: "C:\\Users\\17749\\GolandProjects\\project\\ms_project\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:12379"